#!/usr/bin/env groovy

pipeline {
    agent any
    stages {
        stage('Docker from hub') {
            agent {
                docker { image 'golang:latest'}
            }
            steps {
                sh 'go version'
            }
        }
        stage('Docker from dockerfile') {
            agent {
                dockerfile true 
            }
            steps {
                sh "echo 'Hello, motherfucker'"
            }
        }
    }
}
